export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const UPDATE_CUSTOMER_BETS = 'UPDATE_CUSTOMER_BETS';
export const UPDATE_CUSTOMER_RACES = 'UPDATE_CUSTOMER_RACES';

export const UPDATE_SELECTED_RACE = 'UPDATE_SELECTED_RACE';
export const RESET_SELECTED_RACE = 'RESET_SELECTED_RACE';
